[tool.poetry]
name = "pythonmarch2022tutorials"
version = "0.1.0"
description = ""
authors = ["jarvis0530 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
